"""Edit status column in package table

Revision ID: 65003497934d
Revises: e6e5e7b7e0d9
Create Date: 2021-01-07 13:07:33.027754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65003497934d'
down_revision = 'e6e5e7b7e0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('packages_status_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'status', ['status_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('packages_status_fkey', 'status', ['status'], ['id'])
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
